[package]
name = "XFChess"
version = "0.1.0"
edition = "2021"


[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.15.0"
bevy_egui = "0.29.0"
bevy_renet = "0.0.12"
renet = "0.0.16"
serde = "1.0.208"
tokio = "1.42.0"
bevy-inspector-egui = "0.28.0"
ahash = "0.8.11"